sudo: required

language: php

before_install:
- git remote update
- if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
      git checkout -b master;
    else
      git checkout -b $TRAVIS_PULL_REQUEST_BRANCH;
  fi

script:
- if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
      php ./master/master.php;
    else
      php ./pr/pr.php;
  fi

branches:
  only:
    - master
